### ISSUE TITLE
Keine Anzeige der Gruppenkonfiguration

### ISSUE THREAD

**Issue by KlausGrenoble** [Kuestenschmiede/con4gis_groups#10]
Ist Mitgliederrechte kein einziges Häkchen gesetzt, fehlt die gesamte Anzeige der Gruppenkonfiguration. Es ist dann natürlich auch nicht möglich, ein Häkchen zu setzen.
Gruss Klaus

**Comment by coastforge-tdo** [comment]
Nun, wenn ein Mitglied keinerlei Rechte zum Verändern der Gruppenkonfiguration besitzt, so wird ihm diese Aktion auch nicht angezeigt, das gilt auch für den Gruppenbesitzer, dessen Rechte nur über das Backend definiert werden können; entweder direkt an einer Gruppe, oder über die definierten Standard-Besitzerrechte in der Modulkonfiguration selbst.
Übrigens maskieren die Besitzerrechte die im Frontend einstellbaren Mitgliederrechte; Einem Mitglied können über das Frontend nie mehr Rechte zugesprochen werden, als dem Besitzer.

Liebe Grüße
Tobias
