### ISSUE TITLE
Sprache wechselt auf englisch

### ISSUE THREAD

**Issue by KlausGrenoble** [Kuestenschmiede/con4gis_groups#9]
Im deutschen Browser erscheint die con4gis_groups-Startseite auf deutsch. Ist auch normal. Wählt man eine Gruppe aus, ändert sich die Sprache auf englisch. Ist nicht normal. Nach einem Refresh dieser Seite erscheint diese dann (glücklicherweise) auf deutsch.
Gruss Klaus

**Comment by coastforge-tdo** [comment]
Hallo Klaus,

sind in deiner Installation irgendwelche besonderen Weiterleitungen aktiviert? Ich kann dieses Verhalten bislang leider nicht rekonstruieren. Bei mir wird das Modul auch bei der Auswahl einer Gruppe auf Deutsch angezeigt.

Liebe Grüße

**Comment by KlausGrenoble** [comment]
Muss mich verbessern:
Ich war nicht im m deutschen Browser sondern im französischen. Dann bin ich mit dem Sprachenwechsler auf DE gegangen und habe die Seite "con4gis-groups" aufgerufen. Wählt man eine Gruppe aus, ändert sich die Sprache auf englisch. Allerdings bleibt der Sprachenwechsler auf DE. Aber dass dann nach einem Refresh diese Seite wieder auf deutsch erscheint, ist komisch.
Aber naja, kann man meiner Meinung so lassen und schliessen.
